### ISSUE TITLE
Problem with E-MTAB-2770

### ISSUE THREAD

**Issue by lgeistlinger** [ebi-gene-expression-group/bioconductor-ExpressionAtlas#6] opened 2022-04-20 16:40 UTC
Hi - thanks for a very useful resource. I was until recently able to pull E-MTAB-2770 (RNA-seq data of 1019 human cancer cell lines from the Cancer Cell Line Encyclopedia), but lately I am obtaining a SummarizedExperiment with zero samples:

```
> atlasRes <- ExpressionAtlas::searchAtlasExperiments(
              properties = "Cancer Cell Line Encyclopedia", 
              species = "human" )
> atlasRes
DataFrame with 1 row and 4 columns
    Accession      Species                  Type                  Title
  <character>  <character>           <character>            <character>
1 E-MTAB-2770 Homo sapiens RNA-seq of coding RNA RNA-seq of 1019 huma..
```

```
> ccle.trans <- ExpressionAtlas::getAtlasExperiment("E-MTAB-2770")
> ccle.trans[[1]]
class: RangedSummarizedExperiment 
dim: 58735 0 
metadata(4): pipeline filtering mapping quantification
assays(1): counts
rownames(58735): ENSG00000000003 ENSG00000000005 ... ENSG00000285993
  ENSG00000285994
rowData names(0):
colnames(0):
colData names(4): AtlasAssayGroup organism cell_line disease
```

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] depmap_1.7.1                dplyr_1.0.8                
 [3] graph_1.72.0                ggplot2_3.3.5              
 [5] edgeR_3.36.0                ExpressionAtlas_1.22.1     
 [7] xml2_1.3.2                  limma_3.50.0               
 [9] ExperimentHub_2.2.0         AnnotationHub_3.2.0        
[11] BiocFileCache_2.2.0         dbplyr_2.1.1               
[13] AnnotationDbi_1.56.2        BioPlex_1.1.3              
[15] SummarizedExperiment_1.24.0 Biobase_2.54.0             
[17] GenomicRanges_1.46.1        GenomeInfoDb_1.30.1        
[19] IRanges_2.28.0              S4Vectors_0.32.3           
[21] BiocGenerics_0.40.0         MatrixGenerics_1.6.0       
[23] matrixStats_0.61.0         
```

**Comment by pmb59** [comment] 2022-05-16 09:46
Hi @lgeistlinger thanks for opening an issue.

There was a minimal, but breaking, change in the naming of the experiment summary object in the latest Atlas Release ([8513312](https://github.com/ebi-gene-expression-group/bioconductor-ExpressionAtlas/pull/5/commits/85133128e73fe6784f81f42217b0be45a17f57a8)), that we have corrected in the recent Bioconductor Release (3.15). If you upgrade ExpressionAtlas to [1.24.0](https://www.bioconductor.org/packages/release/bioc/html/ExpressionAtlas.html) it should work fine, please do let us know.

**Comment by lgeistlinger** [comment] 2022-05-16 15:47
Hi @pmb59 : many thanks for getting back to me. I upgraded accordingly to 1.24.0, but unfortunately the SE has still zero columns/samples:

```
> ccle.trans <- ExpressionAtlas::getAtlasExperiment("E-MTAB-2770")
> ccle.trans[[1]]
class: RangedSummarizedExperiment 
dim: 58735 0 
metadata(4): pipeline filtering mapping quantification
assays(1): counts
rownames(58735): ENSG00000000003 ENSG00000000005 ... ENSG00000285993
  ENSG00000285994
rowData names(0):
colnames(0):
colData names(4): AtlasAssayGroup organism cell_line disease
```

```
> sessionInfo()
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur/Monterey 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] ExpressionAtlas_1.24.0      xml2_1.3.3                 
 [3] limma_3.52.0                DESeq2_1.36.0              
 [5] SummarizedExperiment_1.26.1 Biobase_2.56.0             
 [7] MatrixGenerics_1.8.0        matrixStats_0.62.0         
 [9] GenomicRanges_1.48.0        GenomeInfoDb_1.32.1        
[11] IRanges_2.30.0              S4Vectors_0.34.0           
[13] BiocGenerics_0.42.0        

loaded via a namespace (and not attached):
 [1] locfit_1.5-9.5         Rcpp_1.0.8.3           lattice_0.20-45       
 [4] png_0.1-7              Biostrings_2.64.0      assertthat_0.2.1      
 [7] utf8_1.2.2             R6_2.5.1               RSQLite_2.2.14        
[10] httr_1.4.3             ggplot2_3.3.6          pillar_1.7.0          
[13] zlibbioc_1.42.0        rlang_1.0.2            curl_4.3.2            
[16] annotate_1.74.0        blob_1.2.3             Matrix_1.4-1          
[19] splines_4.2.0          BiocParallel_1.30.0    geneplotter_1.74.0    
[22] RCurl_1.98-1.6         bit_4.0.4              munsell_0.5.0         
[25] DelayedArray_0.22.0    compiler_4.2.0         pkgconfig_2.0.3       
[28] tidyselect_1.1.2       KEGGREST_1.36.0        tibble_3.1.7          
[31] GenomeInfoDbData_1.2.8 XML_3.99-0.9           fansi_1.0.3           
[34] crayon_1.5.1           dplyr_1.0.9            bitops_1.0-7          
[37] grid_4.2.0             xtable_1.8-4           gtable_0.3.0          
[40] lifecycle_1.0.1        DBI_1.1.2              magrittr_2.0.3        
[43] scales_1.2.0           cli_3.3.0              cachem_1.0.6          
[46] XVector_0.36.0         genefilter_1.78.0      ellipsis_0.3.2        
[49] vctrs_0.4.1            generics_0.1.2         RColorBrewer_1.1-3    
[52] tools_4.2.0            bit64_4.0.5            glue_1.6.2            
[55] purrr_0.3.4            parallel_4.2.0         fastmap_1.1.0         
[58] survival_3.3-1         AnnotationDbi_1.58.0   colorspace_2.0-3      
[61] BiocManager_1.30.17    memoise_2.0.1
```

I also tried installing the latest version here from github (version 1.25.3) - with unfortunately the same result. Thank you for your attention to this matter.

**Comment by pmb59** [comment] 2022-05-18 10:27
Hi @lgeistlinger
I've done some investigation, and the problem is not not related to the ExpressionAtlas package - it is due to an empty summary experiment object provided in the FTP for this experiment in the latest release. Could you please raise an issue [here](https://www.ebi.ac.uk/support/gxa)? A simple link to this GitHub issue should suffice.

In the meantime, in the [FTP archive folder](http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-MTAB-2770/archive/) for this accession there is a recent summary data file, dated Jan-2022, which contains the full dataset. I'm not sure how this file ended up there, but it should have what you are looking for:

```
> library(ExpressionAtlas)
> load("E-MTAB-2770-atlasExperimentSummary.Rdata.1")
> objects()
[1] "experimentSummary"
> experimentSummary
List of length 1
names(1): rnaseq
> experimentSummary[[1]]
class: RangedSummarizedExperiment 
dim: 58735 1019 
metadata(4): pipeline filtering mapping quantification
assays(1): counts
rownames(58735): ENSG00000000003 ENSG00000000005 ... ENSG00000285993
  ENSG00000285994
rowData names(0):
colnames(1019): SRR8615222 SRR8615223 ... SRR8618318 SRR8618319
colData names(5): AtlasAssayGroup organism cell_line disease
  organism_part
> dim(assay(experimentSummary[[1]]))
[1] 58735  1019
```

thank you for raising this problem - I will am closing the issue now as it is not related to the Bioconductor package.

**Closed by pmb59** 2022-05-18 10:27 UTC
